name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          ls /Applications/
          bash build.sh
