name: CI

on: 
  workflow_dispatch:
    inputs:
      libressl:
        description: 'version'     
        required: true
        default: '3.9.0'
      tags:
        description: 'specify libressl version'

jobs:
  build:
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          export LIBRESSL=${{ github.event.inputs.libressl }}
          bash build.sh
